language: node_js
deploy:
  api_key:
    secure: P0l3+m1bre31u4DoWs66kADc6o4CSuTOpRgwPQvA5Rw/XmAP3XnOL0UID9sLBsIyIrzkJoV54OpFSAeau4kPoTjFSNm+pl6rlX94J0ugZiAKwGHjAqtdCvzIi/QRajXuj3KF6TvQkqnbSdE8sJAdCjr4kqVKcQKkcW5Jc7ZKE5g=
  provider: npm
  email: john@mclear.co.uk
